"""Generate FAKE scorecards for the 2026 event, for testing only.

Writes raw_scores_round_N.json files (plus fake Round 2 skins points) into the
draft config's data dir, in the exact shape jdcvo/playthru.py produces, so the
whole scoring pipeline can run end-to-end before the real PlayThru events
exist.

NOTHING HERE IS REAL. Every entry is synthetic and marked with a FAKE golfer
id. Only ever point this at a data dir used for testing.

Usage:
    python3 tools/make_fake_scores.py [--config event_2026_draft.json] [--seed 20260728]
"""

import argparse
import json
import os
import random
import sys
from datetime import datetime

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from jdcvo.config import EventConfig
from jdcvo.store import LocalStore

FAKE_MARKER = 'FAKE_DATA_DO_NOT_TRUST.txt'


def hole_order_by_difficulty(holes):
    """Hole numbers from hardest (stroke index 1) to easiest."""
    return sorted(holes, key=lambda h: holes[h]['handicap'])


def make_round_card(holes, over_par, rng):
    """Build an 18-hole card finishing ``over_par`` strokes over par.

    ``over_par`` may be negative (scramble formats routinely go under). Dropped
    shots land preferentially on hard holes and gained shots on easy ones, with
    enough randomness that no two cards look alike.
    """
    card = {h: holes[h]['par'] for h in holes}
    hard_first = hole_order_by_difficulty(holes)
    easy_first = list(reversed(hard_first))

    if over_par >= 0:
        # A birdie or two first, so cards aren't monotonically over par.
        birdies = rng.randint(0, 2) if over_par > 3 else 0
        for h in rng.sample(easy_first[:9], birdies):
            card[h] -= 1
        remaining = over_par + birdies
        weights = [19 - holes[h]['handicap'] for h in hard_first]
        guard = 0
        while remaining > 0 and guard < 10000:
            guard += 1
            h = rng.choices(hard_first, weights=weights)[0]
            # No single hole balloons past par + 4.
            if card[h] - holes[h]['par'] >= 4:
                continue
            card[h] += 1
            remaining -= 1
    else:
        remaining = -over_par
        weights = [holes[h]['handicap'] for h in easy_first]
        guard = 0
        while remaining > 0 and guard < 10000:
            guard += 1
            h = rng.choices(easy_first, weights=weights)[0]
            par_h = holes[h]['par']
            floor = par_h - 2 if par_h >= 5 else par_h - 1  # eagles only on par 5s
            if card[h] <= floor or card[h] <= 2:
                continue
            card[h] -= 1
            remaining -= 1

    return {str(h): card[h] for h in sorted(card, key=int)}


def entry(name, style, hole_scores, idx):
    return {
        'name': name,
        'scoring_style': style,
        'golfer_id': f'FAKE{idx:06d}',
        'hole_scores': hole_scores,
        'total_score': sum(hole_scores.values()),
        'timestamp': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--config', default='event_2026_draft.json')
    ap.add_argument('--seed', type=int, default=20260728)
    ap.add_argument('--rounds', default='', help='comma list, default = all')
    args = ap.parse_args()

    rng = random.Random(args.seed)
    cfg = EventConfig(args.config)

    if cfg.google_sheet_key:
        sys.exit(f"REFUSING: {args.config} has a google_sheet_key set. Fake "
                 f"scores must never be publishable. Blank it first.")

    store = LocalStore(cfg.data_dir)
    only = {int(r) for r in args.rounds.split(',') if r.strip()}

    with open(os.path.join(cfg.data_dir, FAKE_MARKER), 'w') as f:
        f.write("Every raw_scores_round_*.json and match_play.json in this "
                "directory is SYNTHETIC test data generated by "
                "tools/make_fake_scores.py. It is not real and must never be "
                "published to the Google Sheet or treated as results.\n")

    handicaps = cfg.handicaps()
    summary = []

    for n in cfg.round_numbers():
        if only and n not in only:
            continue
        rcfg = cfg.round_config(n)
        style = rcfg['scoring_style']
        holes = cfg.course_holes(n)
        par = sum(h['par'] for h in holes.values()) if holes else None

        if style == 'best_ball_individual':
            rows = []
            for i, (name, hcp) in enumerate(sorted(handicaps.items())):
                # In 2025 this group shot roughly handicap + 11 over par
                # (mean 20.1 over on R1, 24.4 on R3). Mirror that relationship
                # rather than assuming everyone plays to their number.
                over = max(2, int(rng.gauss(hcp + 11, 4.0)))
                rows.append(entry(name, style, make_round_card(holes, over, rng), i))
            store.write_raw_scores(n, rows)
            scores = [r['total_score'] for r in rows]
            summary.append(f"R{n} {style}: {len(rows)} players, "
                           f"par {par}, scores {min(scores)}-{max(scores)}")

        elif style == 'team_scramble':
            rows = []
            for i, team in enumerate(cfg.teams()):
                # 2025 team scrambles came in -8 to -4.
                over = int(round(rng.gauss(-6, 1.8)))
                rows.append(entry(team, style,
                                  make_round_card(holes, over, rng), i))
            store.write_raw_scores(n, rows)
            scores = [r['total_score'] for r in rows]
            summary.append(f"R{n} {style}: {len(rows)} teams, "
                           f"par {par}, scores {min(scores)}-{max(scores)}")

        elif style == 'two_man_scramble':
            sep = rcfg.get('pair_separator', ' and ')
            partners = cfg.partners(n)
            seen, rows, i = set(), [], 0
            for name, partner in partners.items():
                key = frozenset((name, partner))
                if key in seen:
                    continue
                seen.add(key)
                # 2025 two-man scrambles came in -10 to 0.
                over = int(round(rng.gauss(-4.5, 3.5)))
                rows.append(entry(f"{name}{sep}{partner}", style,
                                  make_round_card(holes, over, rng), i))
                i += 1
            store.write_raw_scores(n, rows)
            scores = [r['total_score'] for r in rows]
            summary.append(f"R{n} {style}: {len(rows)} pairs, "
                           f"par {par}, scores {min(scores)}-{max(scores)}")

        elif style == 'match_play':
            # Skins/match play points are typed in by hand, not scraped.
            # Fabricate one row per pair so the round has something to score.
            partners = cfg.partners(n)
            seen, rows = set(), []
            for name, partner in partners.items():
                key = frozenset((name, partner))
                if key in seen:
                    continue
                seen.add(key)
                rows.append({'players': [name, partner],
                             'points': rng.choice([0, 0.5, 1, 1.5, 2, 2.5, 3])})
            store.write_match_play(rows)
            summary.append(f"R{n} {style}: {len(rows)} pairs of manual points "
                           f"-> match_play.json")
        else:
            summary.append(f"R{n} {style}: SKIPPED (no generator)")

    print(f"Wrote FAKE data to {cfg.data_dir} (seed {args.seed})")
    for line in summary:
        print('  ' + line)


if __name__ == '__main__':
    main()
